name: Deploy Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '~22'

      # If you have an asset build step, add it here, e.g.:
      # - name: Build assets
      #   run: npm run build-assets

      # If your assets are already in static-resources/, you can skip the build step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static-resources
